//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionStock
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class StockDATAEntities : DbContext
    {
        public StockDATAEntities()
            : base("name=StockDATAEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Category> Category { get; set; }
        public virtual DbSet<ClientBill> ClientBill { get; set; }
        public virtual DbSet<ClientCommand> ClientCommand { get; set; }
        public virtual DbSet<Clients> Clients { get; set; }
        public virtual DbSet<EnterStock> EnterStock { get; set; }
        public virtual DbSet<LeaveStock> LeaveStock { get; set; }
        public virtual DbSet<Product> Product { get; set; }
        public virtual DbSet<ProviderBill> ProviderBill { get; set; }
        public virtual DbSet<ProviderCommand> ProviderCommand { get; set; }
        public virtual DbSet<Providers> Providers { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
